version: 1
disable_existing_loggers: True
formatters:
  # Add a new formatter if it's needed by your application
  basic:
    format: '%(asctime)s %(levelname)-8s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  in_console:
    format: '        %(asctime)s: %(name)-6s %(levelname)-8s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: in_console
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: basic
    # FIXME: log filename should go to output.
    filename: slayer.log
    mode: w
    encoding: utf-8
root:
  level: DEBUG
  propagate: False
  handlers: [console, file]
